version: '3.8'

services:
  mariadb:
    image: docker.io/bitnamilegacy/mariadb:11.8.3
    restart: unless-stopped
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: docker.io/bitnamilegacy/moodle:5.0.2
    restart: unless-stopped
    user: "1001"
    depends_on:
      - mariadb
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=Adminpass123
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_SITE_NAME=Local Moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
